const fs = require('fs').promises;
const path = require('path');
const axios = require('axios');
const { URLSearchParams } = require('url');
const FormData = require('form-data');
const CATALOG = require('./muapi-models.json');

// Server-side port of the Open Generative AI studio's MuAPI client (Open-Generative-AI-main/src/lib/muapi.js).
// Submit: POST /api/v1/{endpoint} · poll: GET /api/v1/predictions/{id}/result · upload: POST /api/v1/upload_file.
// The model catalog (utils/muapi-models.json) is generated by scripts/sync-muapi-models.mjs from the studio's
// packages/studio/src/models.js (Open-Generative-AI-main, plus models only the 2.0.0 release still lists).

const DEFAULT_BASE_URL = 'https://api.muapi.ai';
const DEFAULT_VIDEO_MODEL = 'seedance-2.5-text-to-video';
const DEFAULT_I2V_MODEL = 'seedance-2.5-image-to-video';
const DEFAULT_IMAGE_MODEL = 'nano-banana-pro';
const SUCCESS = new Set(['completed', 'succeeded', 'success']);
const FAILURE = new Set(['failed', 'error', 'cancelled', 'canceled']);
// With a zero balance MuAPI answers "completed" at no cost with the model's catalogue sample
// (…cloudfront.net/webassets/videomodels/…) instead of a generation; that must never reach a video.
const SAMPLE_ASSET = /\/webassets\//i;

const byId = list => new Map(list.map(model => [model.id, model]));
const MODELS = {
  textToVideo: byId(CATALOG.textToVideo),
  imageToVideo: byId(CATALOG.imageToVideo),
  textToImage: byId(CATALOG.textToImage)
};

function resolveMuapiKey(credentials = {}) {
  const creds = credentials.credentials || credentials;
  const key = creds.muapi?.apiKey || process.env.MUAPI_API_KEY || process.env.MUAPI_KEY;
  return key ? String(key).trim() : null;
}

// OAuth 2.0 client_credentials (oc_… / ocs_…), MuAPI's alternative to a plain API key for automated systems.
function resolveMuapiClient(credentials = {}) {
  const creds = credentials.credentials || credentials;
  const clientId = creds.muapi?.clientId || process.env.MUAPI_CLIENT_ID;
  const clientSecret = creds.muapi?.clientSecret || process.env.MUAPI_CLIENT_SECRET;
  return clientId && clientSecret ? { clientId: String(clientId).trim(), clientSecret: String(clientSecret).trim() } : null;
}

function resolveMuapiAuth(credentials = {}) {
  return { apiKey: resolveMuapiKey(credentials), oauth: resolveMuapiClient(credentials) };
}

function safeMuapiError(value) {
  return String(value || 'MuAPI request failed')
    .replace(/(x-api-key|api[_-]?key)["':=\s]+[A-Za-z0-9._-]+/gi, '$1=[redacted]')
    .slice(0, 500);
}

// Picks a value the model accepts: the requested one when allowed, otherwise the closest/default option.
function fitValue(spec = {}, requested) {
  if (Array.isArray(spec.enum) && spec.enum.length) {
    const options = spec.enum.filter(option => option !== 'adaptive' || requested === 'adaptive');
    const exact = options.find(option => String(option).toLowerCase() === String(requested ?? '').toLowerCase());
    if (exact !== undefined) return exact;
    if (typeof options[0] === 'number' && Number.isFinite(Number(requested))) {
      return options.reduce((best, option) => Math.abs(option - requested) < Math.abs(best - requested) ? option : best, options[0]);
    }
    return spec.default !== undefined && options.includes(spec.default) ? spec.default : options[0];
  }
  if (Number.isFinite(Number(requested)) && (spec.min !== undefined || spec.max !== undefined)) {
    return Math.max(spec.min ?? -Infinity, Math.min(spec.max ?? Infinity, Math.round(Number(requested))));
  }
  return requested ?? spec.default;
}

function durationRange(model) {
  const spec = model?.inputs?.duration;
  if (!spec) return { min: 4, max: 10, fixed: null };
  if (Array.isArray(spec.enum)) {
    const values = spec.enum.map(Number).filter(Number.isFinite);
    return { min: Math.min(...values), max: Math.max(...values), fixed: values.length === 1 ? values[0] : null };
  }
  return { min: spec.min ?? 4, max: spec.max ?? 10, fixed: null };
}

// Models that take pixel dimensions instead of an aspect ratio get the largest multiple-of-64 size in range.
function pixelSize(inputs, aspectRatio) {
  const [w, h] = String(aspectRatio).split(':').map(Number);
  const ratio = w > 0 && h > 0 ? w / h : 16 / 9;
  const maxWidth = Math.min(inputs.width.max ?? 1344, 1920);
  const maxHeight = Math.min(inputs.height.max ?? 1344, 1920);
  let width = Math.min(maxWidth, Math.floor(maxHeight * ratio));
  let height = Math.round(width / ratio);
  width = Math.max(inputs.width.min ?? 64, Math.floor(width / 64) * 64);
  height = Math.max(inputs.height.min ?? 64, Math.floor(height / 64) * 64);
  return { width, height };
}

function buildPayload(model, request = {}) {
  const inputs = model.inputs || {};
  const payload = { prompt: String(request.prompt || '') };
  if (inputs.aspect_ratio) payload.aspect_ratio = fitValue(inputs.aspect_ratio, request.aspectRatio || '16:9');
  else if (inputs.width && inputs.height) Object.assign(payload, pixelSize(inputs, request.aspectRatio || '16:9'));
  if (inputs.duration && request.duration !== undefined) payload.duration = fitValue(inputs.duration, Number(request.duration));
  if (inputs.resolution) payload.resolution = fitValue(inputs.resolution, request.resolution);
  // The pipeline lays its own narration over the clips, so native audio stays off unless asked for.
  if (inputs.generate_audio) payload.generate_audio = request.generateAudio === true;
  if (inputs.num_images) payload.num_images = 1;
  if (request.imageUrl) {
    const field = model.imageField || 'image_url';
    payload[field] = field.endsWith('_list') ? [request.imageUrl] : request.imageUrl;
  }
  if (request.lastImageUrl && model.lastImageField) payload[model.lastImageField] = request.lastImageUrl;
  return payload;
}

function normalizeResult(result = {}, requestId = null) {
  const raw = String(result.status || 'processing').toLowerCase();
  const status = SUCCESS.has(raw) ? 'succeeded' : FAILURE.has(raw) ? (raw.startsWith('cancel') ? 'cancelled' : 'failed') : raw === 'queued' || raw === 'pending' ? 'queued' : 'running';
  const outputs = Array.isArray(result.outputs) ? result.outputs : [];
  const first = outputs[0];
  const outputUrl = (typeof first === 'string' ? first : first?.url) || result.url || result.output?.url || null;
  const sample = status === 'succeeded' && SAMPLE_ASSET.test(String(outputUrl || ''));
  const detail = sample
    ? 'MuAPI returned its sample asset instead of a generation (the account balance is probably 0)'
    : typeof result.error === 'string' ? result.error : result.error?.message || (status === 'failed' ? result.message : null);
  return {
    externalTaskId: result.request_id || result.id || requestId,
    rawStatus: raw,
    status: sample ? 'failed' : status,
    outputUrl: sample ? null : outputUrl,
    error: detail ? safeMuapiError(detail) : null,
    refunded: result.cost?.refunded === true
  };
}

class MuapiClient {
  constructor(options = {}) {
    this.apiKey = options.apiKey || null;
    this.oauth = options.oauth || null;
    this.token = null;
    this.baseUrl = String(options.baseUrl || process.env.MUAPI_BASE_URL || DEFAULT_BASE_URL).replace(/\/$/, '');
    this.http = options.http || axios;
    this.sleep = options.sleep || (ms => new Promise(resolve => setTimeout(resolve, ms)));
    this.uploads = new Map();
  }

  isConfigured() { return Boolean(this.apiKey || this.oauth); }

  // The API key wins when both are set; OAuth tokens last an hour and are refreshed a minute early.
  async authHeaders(forceRefresh = false) {
    if (this.apiKey) return { 'x-api-key': this.apiKey };
    if (!forceRefresh && this.token && Date.now() < this.token.expiresAt) return { Authorization: `Bearer ${this.token.value}` };
    const body = new URLSearchParams({ grant_type: 'client_credentials', client_id: this.oauth.clientId, client_secret: this.oauth.clientSecret });
    const response = await this.http.request({
      method: 'POST', url: `${this.baseUrl}/oauth/token`, data: body.toString(),
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, timeout: 30000, validateStatus: () => true
    });
    if (response.status !== 200 || !response.data?.access_token) {
      const error = new Error(`MuAPI OAuth token request failed (${response.status})`);
      error.status = response.status;
      throw error;
    }
    const lifetime = Math.max(120, Number(response.data.expires_in || 3600)) * 1000;
    this.token = { value: response.data.access_token, expiresAt: Date.now() + lifetime - 60000 };
    return { Authorization: `Bearer ${this.token.value}` };
  }

  async request(config, retried = false) {
    if (!this.isConfigured()) throw new Error('MuAPI credentials are not configured (MUAPI_API_KEY or MUAPI_CLIENT_ID/MUAPI_CLIENT_SECRET)');
    const response = await this.http.request({
      ...config,
      url: `${this.baseUrl}${config.url}`,
      headers: { ...await this.authHeaders(), ...(config.headers || {}) },
      validateStatus: () => true
    });
    if ((response.status === 401 || response.status === 403) && !this.apiKey && !retried) {
      await this.authHeaders(true);
      return this.request(config, true);
    }
    if (response.status < 200 || response.status >= 300) {
      const body = typeof response.data === 'string' ? response.data : JSON.stringify(response.data || {});
      const error = new Error(safeMuapiError(`MuAPI ${response.status}: ${body.slice(0, 200)}`));
      error.status = response.status;
      throw error;
    }
    return response.data || {};
  }

  async submit(endpoint, payload) {
    if (!/^[a-z0-9][a-z0-9._/-]*$/i.test(endpoint) || endpoint.includes('..')) throw new Error('Invalid MuAPI endpoint');
    const data = await this.request({ method: 'POST', url: `/api/v1/${endpoint}`, data: payload, headers: { 'Content-Type': 'application/json' }, timeout: 120000 });
    const requestId = data.request_id || data.id;
    // Some endpoints answer synchronously with the finished result.
    return requestId ? { requestId, immediate: null } : { requestId: null, immediate: normalizeResult(data) };
  }

  async balance() {
    const data = await this.request({ method: 'GET', url: '/api/v1/account/balance', timeout: 30000 });
    return { balance: Number(data.balance || 0), currency: data.currency || 'USD' };
  }

  async result(requestId) {
    const data = await this.request({ method: 'GET', url: `/api/v1/predictions/${encodeURIComponent(requestId)}/result`, timeout: 30000 });
    return normalizeResult(data, requestId);
  }

  // Local files have to be hosted before a model can read them; the returned URL is cached per file.
  async uploadFile(filePath) {
    if (!filePath) return null;
    if (/^https?:\/\//i.test(filePath)) return filePath;
    if (this.uploads.has(filePath)) return this.uploads.get(filePath);
    const form = new FormData();
    form.append('file', await fs.readFile(filePath), path.basename(filePath));
    const data = await this.request({ method: 'POST', url: '/api/v1/upload_file', data: form, headers: form.getHeaders(), timeout: 120000, maxBodyLength: Infinity });
    const url = data.url || data.file_url || data.data?.url;
    if (!url) throw new Error('MuAPI upload returned no URL');
    this.uploads.set(filePath, url);
    return url;
  }

  async waitFor(requestId, { intervalMs = 3000, timeoutMs = 10 * 60 * 1000 } = {}) {
    const started = Date.now();
    for (;;) {
      await this.sleep(intervalMs);
      let result;
      try {
        result = await this.result(requestId);
      } catch (error) {
        if (!(error.status >= 500)) throw error;
        result = null;
      }
      if (result && ['succeeded', 'failed', 'cancelled'].includes(result.status)) return result;
      if (Date.now() - started > timeoutMs) throw new Error(`Timed out waiting for MuAPI request ${requestId}`);
    }
  }

  async generateImage(prompt, outputPath, options = {}) {
    const modelId = options.model || process.env.MUAPI_IMAGE_MODEL || DEFAULT_IMAGE_MODEL;
    const model = MODELS.textToImage.get(modelId);
    if (!model) throw new Error(`Unknown MuAPI image model: ${modelId}`);
    const payload = buildPayload(model, { prompt, aspectRatio: options.aspectRatio || '16:9', resolution: options.resolution || process.env.MUAPI_IMAGE_RESOLUTION || '2k' });
    const submitted = await this.submit(model.endpoint, payload);
    const result = submitted.immediate || await this.waitFor(submitted.requestId, options);
    if (result.status !== 'succeeded' || !result.outputUrl) {
      throw new Error(result.error || `MuAPI image generation ${result.rawStatus}${result.refunded ? ' (refunded)' : ''}`);
    }
    const response = await this.http.get(result.outputUrl, { responseType: 'arraybuffer', timeout: 120000 });
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, Buffer.from(response.data));
    return { path: outputPath, model: modelId, requestId: submitted.requestId };
  }
}

module.exports = {
  DEFAULT_BASE_URL,
  DEFAULT_VIDEO_MODEL,
  DEFAULT_I2V_MODEL,
  DEFAULT_IMAGE_MODEL,
  MODELS,
  MuapiClient,
  resolveMuapiKey,
  resolveMuapiClient,
  resolveMuapiAuth,
  buildPayload,
  durationRange,
  fitValue,
  normalizeResult
};
